### ISSUE TITLE
Hi, could you give more detail about how to install OpenRoadEd?

### ISSUE THREAD

**Issue by gaopenggang** [fhwedel-hoe/OpenRoadEd#2]
Hi, could you give more detail about how to install OpenRoadEd?
could it be used in ubuntu 16.04 now?
Thanks

**Comment by fhwedel-hoe** [comment]
No, I cannot – since there is no need to install it. Compile it (with qt creator), then run it. The binary should be located at `build/OpenRoadEd`.

I expect, it can be used in Ubuntu 16.04.

Bear in mind that there is a show-stopping bug: The display window is stuck at 100x30 pixels. I could not figure out how to fix this.

**Comment by ebadi** [comment]
@fhwedel-hoe  With recent changes in documentation, I guess this issue can also be closed. 
I guess it is more convenient to release prebuild Linux release binaries for the end user once the remaining issues are fixed.

**Comment by fhwedel-hoe** [comment]
Yes, I'll close this issue.

I do not plan to offer binary releases. People tend not to read the documentation or the "known issues" sections and then complain about stuff not working.
